export const FETCHING_INTRO_REQUESTED = 'FETCHING_INTRO_REQUESTED';
export const FETCHING_INTRO = 'FETCHING_INTRO';
export const FETCHING_INTRO_SUCCEEDED = 'FETCHING_INTRO_REQUESTED_SUCCEEDED';
export const FETCHING_INTRO_FAILED = 'FETCHING_INTRO_REQUESTED_FAILED';

export const FETCHING_RECENT_REQUESTED = 'FETCHING_RECENT_REQUESTED';
export const FETCHING_RECENT = 'FETCHING_RECENT';
export const FETCHING_RECENT_SUCCEEDED = 'FETCHING_RECENT_REQUESTED_SUCCEEDED';
export const FETCHING_RECENT_FAILED = 'FETCHING_RECENT_REQUESTED_FAILED';

export const GEO_REQUESTED = 'GEO_REQUESTED';
export const FETCHING_GEO_REQUESTED = 'FETCHING_GEO_REQUESTED';
export const FETCHING_GEO_SUCCEEDED = 'FETCHING_GEO_SUCCEEDED';
export const FETCHING_GEO_FAILED = 'FETCHING_GEO_FAILED';

export const EDITOR_CATEGORY = 'letter-from-editor';