export const FETCHING_FREE_SEARCH = 'FETCHING_FREE_SEARCH';
export const FETCHING_FREE_SEARCH_SUCCEEDED = 'FETCHING_FREE_SEARCH_SUCCEEDED';
export const FETCHING_FREE_SEARCH_FAILED = 'FETCHING_FREE_SEARCH_FAILED';
export const FETCHING_FREE_SEARCH_REQUESTED = 'FETCHING_FREE_SEARCH_REQUESTED';
export const CLEAN_SEARCH = 'CLEAN_SEARCH';

export const FETCHING_PAGINATED_FREE_SEARCH_SUCCEEDED = 'FETCHING_PAGINATED_FREE_SEARCH_SUCCEEDED';
export const FETCHING_PAGINATED_FREE_SEARCH_FAILED = 'FETCHING_PAGINATED_FREE_SEARCH_FAILED';
export const FETCHING_PAGINATED_FREE_SEARCH_REQUESTED = 'FETCHING_PAGINATED_FREE_SEARCH_REQUESTED';