export const FETCHING_USER_SETTINGS = 'FETCHING_USER_SETTINGS';
export const FETCHING_USER_SETTINGS_SUCCEEDED = 'FETCHING_USER_SETTINGS_SUCCEEDED';
export const FETCHING_USER_SETTINGS_FAILED = 'FETCHING_USER_SETTINGS_FAILED';
export const FETCHING_USER_SETTINGS_REQUESTED = 'FETCHING_USER_SETTINGS_REQUESTED';

export const FETCHING_USER = 'FETCHING_USER';
export const FETCHING_USER_SUCCEEDED = 'FETCHING_USER_SUCCEEDED';
export const FETCHING_USER_FAILED = 'FETCHING_USER_FAILED';
export const FETCHING_USER_REQUESTED = 'FETCHING_USER_REQUESTED';

export const SET_POPUP_VISIBILITY = 'SET_POPUP_VISIBILITY';

export const UPDATING_USER_SETTINGS = 'UPDATING_USER_SETTINGS';
export const UPDATING_USER_SETTINGS_SUCCEEDED = 'UPDATING_USER_SETTINGS_SUCCEEDED';
export const UPDATING_USER_SETTINGS_FAILED = 'UPDATING_USER_SETTINGS_FAILED';
export const UPDATING_USER_SETTINGS_REQUESTED = 'UPDATING_USER_SETTINGS_REQUESTED';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const ADD_CHANNEL = 'ADD_CHANNEL';
export const REMOVE_CHANNEL = 'REMOVE_CHANNEL';

export const FETCHING_CHANNELS = 'FETCHING_CHANNELS';
export const FETCHING_CHANNELS_SUCCEEDED = 'FETCHING_CHANNELS_SUCCEEDED';
export const FETCHING_CHANNELS_FAILED = 'FETCHING_CHANNELS_FAILED';
export const FETCHING_CHANNELS_REQUESTED = 'FETCHING_CHANNELS_REQUESTED';

export const SET_DEFAULT_PLUS = 'SET_DEFAULT_PLUS';
